# Generated by Django 6.1 on 2026-09-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ausgabe',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='Thema',
            new_name='Topic',
        ),
        migrations.AlterModelTable(
            name='expense',
            table='pool_ausgabe',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='pool_thema',
        ),
    ]
