# Generated by Django 6.1 on 2026-09-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_rename_ausgabe_expense_rename_thema_topic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='thema',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='thema',
            new_name='topic',
        ),
    ]
