# Generated by Django 6.1 on 2026-09-30 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_rename_thema_expense_topic_rename_thema_person_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='betrag',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='erstellt_am',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='beschreibung',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='erstellt_am',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='titel',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='expense',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pool.person'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pool.topic'),
        ),
        migrations.AlterField(
            model_name='person',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='pool.topic'),
        ),
    ]
