# Generated by Django 6.1 on 2026-10-07 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_rename_betrag_expense_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
    ]
