# Generated by Django 6.1 on 2026-10-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0006_expense_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
    ]
