# Generated by Django 6.1 on 2026-10-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0008_expense_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
    ]
